spring:
  datasource:
    url: jdbc:h2:mem:customers
    username: mc9
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
swagger:
  enabled: true
  title: bookings
  description:
  version: 1.0
