server:
  servlet:
    context-path: /api/poli
  port: 9082
spring:
  application:
    name: movie
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
